<?php

namespace ContainerXxjx8UD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotesDairyOfSuccessServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Modules\NotesDairyOfSuccess\NotesDairyOfSuccessService' shared autowired service.
     *
     * @return \App\Modules\NotesDairyOfSuccess\NotesDairyOfSuccessService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Modules'.\DIRECTORY_SEPARATOR.'NotesDairyOfSuccess'.\DIRECTORY_SEPARATOR.'NotesDairyOfSuccessService.php';

        return $container->privates['App\\Modules\\NotesDairyOfSuccess\\NotesDairyOfSuccessService'] = new \App\Modules\NotesDairyOfSuccess\NotesDairyOfSuccessService(($container->privates['App\\Repository\\NoteDairyOfSuccessRepository'] ?? $container->load('getNoteDairyOfSuccessRepositoryService')));
    }
}
